export default {
  SET_TOKEN: {
    REQUEST: 'SET_TOKEN_REQUEST',
    SUCCESS: 'SET_TOKEN_SUCCESS',
    FAILURE: 'SET_TOKEN_FAILURE',
  },
  GET_USER_DATA: {
    REQUEST: 'GET_USER_DATA_REQUEST',
    SUCCESS: 'GET_USER_DATA_SUCCESS',
    FAILURE: 'GET_USER_DATA_FAILURE',
  },
  GET_CODE: {
    REQUEST: 'GET_CODE_REQUEST',
    SUCCESS: 'GET_CODE_SUCCESS',
    FAILURE: 'GET_CODE_FAILURE',
  },
  LOGIN: {
    REQUEST: 'LOGIN_REQUEST',
    SUCCESS: 'LOGIN_SUCCESS',
    FAILURE: 'LOGIN_FAILURE',
  },
  LOGOUT: {
    REQUEST: 'LOGOUT_REQUEST',
    SUCCESS: 'LOGOUT_SUCCESS',
    FAILURE: 'LOGOUT_FAILURE',
  },
  UPDATE_USER_DATA: {
    REQUEST: 'UPDATE_USER_DATA_REQUEST',
    SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
    FAILURE: 'UPDATE_USER_DATA_FAILURE',
  },
};
